# Generated by Django 5.2.1 on 2025-05-14 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_request', models.CharField(choices=[('electrical_appliances', 'Електроприлади'), ('electricity', 'Електрика'), ('plumbing', 'Сантехніка'), ('heating', 'Опалення'), ('ventilation', 'Вентиляція'), ('internet', 'Інтернет'), ('furniture', 'Меблі'), ('windows_doors', 'Вікна / Двері'), ('other', 'Інше')], max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'В обробці'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено'), ('done', 'Виконано'), ('on_check', 'На перевірці')], default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
