# Generated by Django 5.2.1 on 2025-05-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('job_position', models.CharField(choices=[('assistant', 'Асистент'), ('senior_lecturer', 'Старший викладач'), ('associate_professor', 'Доцент'), ('professor', 'Професор'), ('head_of_department', 'Завідувач кафедри')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('job_position', models.CharField(choices=[('assistant', 'Асистент'), ('senior_lecturer', 'Старший викладач'), ('associate_professor', 'Доцент'), ('professor', 'Професор'), ('head_of_department', 'Завідувач кафедри')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('faculty', models.CharField(choices=[('Автомобілів', 'Автомобілів'), ('Виробництва, ремонту та матеріалознавства', 'Виробництва, ремонту та матеріалознавства'), ('Вищої математики', 'Вищої математики'), ('Двигунів і теплотехніки', 'Двигунів і теплотехніки'), ('Дорожньо-будівельних матеріалів і хімії', 'Дорожньо-будівельних матеріалів і хімії'), ('Екології та технологій захисту навколишнього середовища', 'Екології та технологій захисту навколишнього середовища'), ('Економіки', 'Економіки'), ('Інженерії машин транспортного будівництва', 'Інженерії машин транспортного будівництва'), ('Іноземних мов', 'Іноземних мов'), ('Іноземної філології та перекладу', 'Іноземної філології та перекладу'), ('Інформаційних систем і технологій', 'Інформаційних систем і технологій'), ('Інформаційно-аналітичної діяльності та інформаційної безпеки', 'Інформаційно-аналітичної діяльності та інформаційної безпеки'), ('Комп’ютерної, інженерної графіки та дизайну', 'Комп’ютерної, інженерної графіки та дизайну'), ('Конституційного та адміністративного права', 'Конституційного та адміністративного права'), ('Менеджменту', 'Менеджменту'), ('Міжнародних перевезень та митного контролю', 'Міжнародних перевезень та митного контролю'), ('Мостів, тунелів та гідротехнічних споруд', 'Мостів, тунелів та гідротехнічних споруд'), ('Опору матеріалів і машинознавства', 'Опору матеріалів і машинознавства'), ('Системного проєктування об’єктів транспортної інфраструктури та геодезії', 'Системного проєктування об’єктів транспортної інфраструктури та геодезії'), ('Теоретичної та прикладної механіки', 'Теоретичної та прикладної механіки'), ('Теорії та історії держави і права', 'Теорії та історії держави і права'), ('Технічної експлуатації автомобілів та автосервісу', 'Технічної експлуатації автомобілів та автосервісу'), ('Tранспортних систем та безпеки дорожнього руху', 'Tранспортних систем та безпеки дорожнього руху'), ('Tранспортних технологій', 'Tранспортних технологій'), ('Транспортного будівництва та управління майном', 'Транспортного будівництва та управління майном'), ('Транспортного права та логістики', 'Транспортного права та логістики'), ('Туризму', 'Туризму'), ('Фізичного виховання і спорту', 'Фізичного виховання і спорту'), ('Філософії та педагогіки', 'Філософії та педагогіки'), ('Фінанси, облік і аудит', 'Фінанси, облік і аудит')], max_length=200)),
                ('group', models.CharField(max_length=50)),
            ],
        ),
    ]
