# Generated by Django 5.2.1 on 2025-05-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lecturercode_managercode_studentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('lecturer', 'Викладач'), ('manager', 'Менеджер')], max_length=20),
        ),
    ]
