# Generated by Django 5.2.1 on 2025-05-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_request_assigned_company_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'В обробці'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено'), ('done', 'Виконано'), ('on_check', 'На перевірці'), ('empty', 'Чернетка')], default='pending', max_length=50),
        ),
    ]
