# Generated by Django 5.2.1 on 2025-05-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_request_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='work_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
