# Generated by Django 5.2.1 on 2025-05-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_requestimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='photo',
        ),
    ]
