# Generated by Django 5.2.1 on 2025-05-28 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_request_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('university', 'Університет'), ('dormitory', 'Гуртожиток')], max_length=20)),
                ('street_name', models.CharField(max_length=100)),
                ('building_number', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='entrance_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='room_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'В обробці'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено'), ('done', 'Виконано'), ('on_check', 'На перевірці'), ('empty', 'Чернетка')], default='empty', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='location_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.locationunit'),
        ),
    ]
