# Generated by Django 5.2.1 on 2025-05-28 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_locationunit_request_entrance_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='location_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.locationunit'),
            preserve_default=False,
        ),
    ]
