# Generated by Django 5.2.1 on 2025-05-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_request_location_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'В обробці'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено'), ('done', 'Виконано'), ('on_check', 'В процесі'), ('empty', 'Чернетка')], default='empty', max_length=50),
        ),
    ]
