# Generated by Django 5.2.1 on 2025-06-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='room_number',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
